// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEU4-PDl76b28H6Dvp-MdYql0V2hSjLGk',
    appId: '1:20079332996:web:16d6475a7e890edff9bcd1',
    messagingSenderId: '20079332996',
    projectId: 'student-todo-app-1536b',
    authDomain: 'student-todo-app-1536b.firebaseapp.com',
    storageBucket: 'student-todo-app-1536b.firebasestorage.app',
    measurementId: 'G-3M5ZWMHSF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNK2GLRatV8x2FfCP2vF0MKWVl5u0hPh0',
    appId: '1:20079332996:android:ba2bff99c99ea8a2f9bcd1',
    messagingSenderId: '20079332996',
    projectId: 'student-todo-app-1536b',
    storageBucket: 'student-todo-app-1536b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnTKuL9rTLtpzBAdwfB7VIyP7x7dFgYjo',
    appId: '1:20079332996:ios:75ff78fdbcea479ef9bcd1',
    messagingSenderId: '20079332996',
    projectId: 'student-todo-app-1536b',
    storageBucket: 'student-todo-app-1536b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnTKuL9rTLtpzBAdwfB7VIyP7x7dFgYjo',
    appId: '1:20079332996:ios:75ff78fdbcea479ef9bcd1',
    messagingSenderId: '20079332996',
    projectId: 'student-todo-app-1536b',
    storageBucket: 'student-todo-app-1536b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEU4-PDl76b28H6Dvp-MdYql0V2hSjLGk',
    appId: '1:20079332996:web:3ae1e5f751fca240f9bcd1',
    messagingSenderId: '20079332996',
    projectId: 'student-todo-app-1536b',
    authDomain: 'student-todo-app-1536b.firebaseapp.com',
    storageBucket: 'student-todo-app-1536b.firebasestorage.app',
    measurementId: 'G-4GSD9Q8DXN',
  );
}
